FROM amazonlinux:1

RUN yum update -y \
    && yum install -y python36 python36-pip zip \
    && yum clean all -y \
    && rm -rf /var/cache/yum \
    && update-alternatives --set python /usr/bin/python3.6

RUN pip install --upgrade pip \ 
    && ln -s /usr/local/bin/pip /usr/bin/pip

COPY builder-py3.sh /bin/builder.sh
RUN chmod 755 /bin/builder.sh

ENTRYPOINT [ "/bin/builder.sh" ]
